services:
  - type: web
    name: ai-chatbot
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        value: din-api-nøgle-her
